TRANSLATIONS = {
    "en": {
        "title": "AI Farming Assistant",
        "language_select": "Select Language",
        "mode_select": "Choose Service",
        "crop_rec": "Crop Suggestion",
        "irrigation": "Irrigation Help",
        "disease": "Disease Check",
        "chat": "Smart Talk",
        "location": "Location (State/District)",
        "season": "Season",
        "profit": "Profit Priority",
        "soil": "Soil Type (Optional)",
        "water": "Water Availability",
        "get_recommendation": "Get Crop Suggestions",
        "get_irrigation": "Get Irrigation Advice",
        "upload_image": "Upload Crop Image",
        "low": "Low",
        "medium": "Medium",
        "high": "High",
        "kharif": "Kharif (Monsoon)",
        "rabi": "Rabi (Winter)",
        "zaid": "Zaid (Summer)",
        "voice_btn": "Press to Speak",
        "voice_stop": "Stop Recording",
        "conf_level": "Confidence Level",
        "risks": "Risk Factors",
        "assumptions": "Assumptions",
        "disclaimer": "Note: This is AI advice. Consult experts locally.",
        "input_placeholder": "Type your message here...",
        "crop_name_opt": "Crop Name (Optional)",
        "welcome": "Hello Farmer! How can I help you today? You can ask for crop suggestions, irrigation help, or disease check.",
        "ask_category": "What would you like to know about? (Crops / Irrigation / Disease)",
        "ask_short_question": "Please tell me what's on your mind.",
        "processing_voice": "Listening to your voice...",
        "ai_speaking": "AI is speaking...",
        "category_prompt": "I am an AI assistant. Tell me, do you want crop suggestions, irrigation help, or disease check?",
        "q_location": "Where is your farm located? (District and State)",
        "q_season": "Which season is it? (Kharif, Rabi, or Zaid)",
        "q_profit": "What is your profit priority? (Low, Medium, or High)",
        "q_soil": "What is the soil type? (You can say 'next' to skip)",
        "q_water": "How is the water availability? (You can say 'next' to skip)",
        "q_crop": "Which crop are you asking about?",
        "q_rainfall": "How is the rainfall in your area?",
        "nitrogen": "Nitrogen (N)",
        "phosphorus": "Phosphorus (P)",
        "potassium": "Potassium (K)",
        "optional_hint": "(Optional: say 'next' or 'skip')",
        "finishing": "Thank you. Let me analyze that for you...",
    },
    "hi": {
        "title": "एआई खेती सहायक",
        "language_select": "भाषा चुनें",
        "mode_select": "सेवा चुनें",
        "crop_rec": "फसल सुझाव",
        "irrigation": "सिंचाई सहायता",
        "disease": "रोग की जांच",
        "chat": "स्मार्ट बातचीत",
        "location": "स्थान (राज्य/जिला)",
        "season": "मौसम",
        "profit": "लाभ प्राथमिकता",
        "soil": "मिट्टी का प्रकार (वैकल्पिक)",
        "water": "पानी की उपलब्धता",
        "get_recommendation": "फसल के सुझाव प्राप्त करें",
        "get_irrigation": "सिंचाई की सलाह लें",
        "upload_image": "फसल की फोटो अपलोड करें",
        "low": "कम",
        "medium": "मध्यम",
        "high": "अधिक",
        "kharif": "खरीफ (मानसून)",
        "rabi": "रबी (सर्दी)",
        "zaid": "जायद (गर्मी)",
        "voice_btn": "बोलने के लिए दबाएं",
        "voice_stop": "रिकॉर्डिंग रोकें",
        "conf_level": "विश्वास स्तर",
        "risks": "जोखिम कारक",
        "assumptions": "मान्यताएं",
        "disclaimer": "नोट: यह एआई सलाह है। स्थानीय विशेषज्ञों से सलाह लें।",
        "input_placeholder": "अपना संदेश यहाँ लिखें...",
        "crop_name_opt": "फसल का नाम (वैकल्पिक)",
        "welcome": "नमस्ते किसान भाई! मैं आपकी क्या मदद कर सकता हूँ? आप फसल सुझाव, सिंचाई सहायता या रोग जांच के बारे में पूछ सकते हैं।",
        "ask_category": "आप किस बारे में जानना चाहेंगे? (फसल / सिंचाई / रोग)",
        "ask_short_question": "कृपया मुझे बताएं कि आपके मन में क्या है।",
        "processing_voice": "आपकी आवाज़ सुन रहा हूँ...",
        "ai_speaking": "एआई बोल रहा है...",
        "category_prompt": "मैं एक एआई सहायक हूँ। मुझे बताएं, क्या आप फसल सुझाव, सिंचाई सहायता या रोग जांच चाहते हैं?",
        "q_location": "आपका खेत कहाँ है? (ज़िला और राज्य बताएं)",
        "q_season": "अभी कौन सा सीज़न है? (खरीफ, रबी, या जायद)",
        "q_profit": "आपकी लाभ प्राथमिकता क्या है? (कम, मध्यम, या उच्च)",
        "q_soil": "मिट्टी का प्रकार क्या है? (छोड़ने के लिए 'अगला' कहें)",
        "q_water": "पानी की उपलब्धता कैसी है? (छोड़ने के लिए 'अगला' कहें)",
        "q_crop": "आप किस फसल के बारे में पूछ रहे हैं?",
        "q_rainfall": "आपके क्षेत्र में वर्षा कैसी है?",
        "nitrogen": "नाइट्रोजन (N)",
        "phosphorus": "फास्फोरस (P)",
        "potassium": "पोटेशियम (K)",
        "optional_hint": "(वैकल्पिक: 'अगला' या 'छोड़ें' कहें)",
        "finishing": "धन्यवाद। मुझे आपके लिए इसका विश्लेषण करने दें...",
    }
}

class LanguageHandler:
    def __init__(self, lang="en"):
        self.lang = lang

    def set_language(self, lang):
        self.lang = lang

    def get_text(self, key):
        return TRANSLATIONS.get(self.lang, TRANSLATIONS["en"]).get(key, key)

language_handler = LanguageHandler()
